# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Stephenson (macsteps)
email: macsteps [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  A record of development work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://http://macsteps.github.io/" # the base hostname & protocol for your site
twitter_username: scottstephenson
github_username: macsteps

# Build settings
markdown: kramdown
